from collections.abc import Callable
from enum import Enum
from types import EllipsisType
from typing import TypeVar, overload

F = TypeVar("F")
E = TypeVar("E", bound=Enum)

class Context:
    invoked_subcommand: str | None

class Exit(Exception):
    def __init__(self, code: int = 0) -> None: ...

class Typer:
    def __init__(
        self,
        *,
        no_args_is_help: bool = ...,
        help: str | None = ...,
    ) -> None: ...
    def __call__(self) -> None: ...
    def command(
        self,
        name: str | None = ...,
        *,
        help: str | None = ...,
    ) -> Callable[[F], F]: ...
    def callback(
        self,
        *,
        invoke_without_command: bool = ...,
    ) -> Callable[[F], F]: ...
    def add_typer(self, typer_instance: Typer, *, name: str) -> None: ...

class BadParameter(Exception):
    def __init__(self, message: str) -> None: ...

class OptionInfo:
    def __init__(self, *args: object, **kwargs: object) -> None: ...

@overload
def Option(default: EllipsisType, /, *param_decls: str, help: str | None = ...) -> str: ...
@overload
def Option(default: EllipsisType, /, help: str | None = ...) -> str: ...
@overload
def Option(default: list[str], /, *param_decls: str, help: str | None = ...) -> list[str]: ...
@overload
def Option(default: list[str], /, help: str | None = ...) -> list[str]: ...
@overload
def Option(default: str, /, *param_decls: str, help: str | None = ...) -> str: ...
@overload
def Option(default: str, /, help: str | None = ...) -> str: ...
@overload
def Option(default: bool, /, *param_decls: str, help: str | None = ...) -> bool: ...
@overload
def Option(default: bool, /, help: str | None = ...) -> bool: ...
@overload
def Option(default: int, /, *param_decls: str, help: str | None = ...) -> int: ...
@overload
def Option(default: int, /, help: str | None = ...) -> int: ...
@overload
def Option(default: None, /, *param_decls: str, help: str | None = ...) -> None: ...
@overload
def Option(default: None, /, help: str | None = ...) -> None: ...
@overload
def Option(default: E, /, *param_decls: str, help: str | None = ...) -> E: ...
@overload
def Option(default: E, /, help: str | None = ...) -> E: ...
@overload
def Argument(default: EllipsisType, /, *param_decls: str, help: str | None = ...) -> str: ...
@overload
def Argument(default: str, /, *param_decls: str, help: str | None = ...) -> str: ...
def echo(message: object | None = ..., *, err: bool = ...) -> None: ...
