class Error(Exception): ...
class IntegrityError(Error): ...

class Row:
    def __getitem__(self, idx: int | str) -> object: ...
    def keys(self) -> list[str]: ...

class Cursor:
    def fetchone(self) -> Row | None: ...
    def fetchall(self) -> list[Row]: ...
    rowcount: int

class Connection:
    def execute(self, sql: str, parameters: tuple[object, ...] | list[object] = ...) -> Cursor: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    isolation_level: str | None
    row_factory: object | None

def connect(database: str) -> Connection: ...
